// <auto-generated />
using IssueStock.Demo.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IssueStock.Demo.API.Migrations
{
    [DbContext(typeof(StockContext))]
    [Migration("20230530163535_SeedData-StockItems")]
    partial class SeedDataStockItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IssueStock.Demo.API.Models.StockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StockItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "C001",
                            Description = "abc Pvt Ltd description",
                            Name = "Company abc Pvt Ltd"
                        },
                        new
                        {
                            Id = 2,
                            Code = "C002",
                            Description = "pqr Pvt Ltd description",
                            Name = "Company pqr Pvt Ltd"
                        },
                        new
                        {
                            Id = 3,
                            Code = "C003",
                            Description = "abc xyz Ltd description",
                            Name = "Company xyz Pvt Ltd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
